### ISSUE TITLE
Error installing DendroPy along Python 2.7 on Mac OS

### ISSUE THREAD

**Issue by Ruubster** [jeetsukumaran/DendroPy#73] opened 2017-01-13 10:56 UTC
Dear all, 

I've been trying to install DendroPy using pip and the GitHub repository. Both conda and pip install didn't work for me. 

Using the command:

>>> conda install -c ericmjl dendropy=4.1.0

UnsatisfiableError: The following specifications were found to be in conflict:
  - dendropy 4.1.0*
  - python 2.7*
Use "conda info <package>" to see the dependencies for each package.

pip install tells me: 
>>> sudo pip install -U dendropy

Collecting dendropy
  Downloading DendroPy-4.2.0.tar.gz (16.7MB)
    100% |████████████████████████████████| 16.7MB 38kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-build-p12Yma/dendropy/setup.py", line 35, in <module>
        from dendropy import __version__, revision_description, description
      File "dendropy/__init__.py", line 24, in <module>
        from dendropy.dataio.nexusprocessing import get_rooting_argument
      File "dendropy/dataio/__init__.py", line 20, in <module>
        from dendropy.dataio import newickreader
      File "dendropy/dataio/newickreader.py", line 27, in <module>
        from dendropy.utility.textprocessing import StringIO
      File "dendropy/utility/textprocessing.py", line 40, in <module>
        ENCODING = locale.getdefaultlocale()[1]
      File "/Users/rubenbakker/anaconda/lib/python2.7/locale.py", line 545, in getdefaultlocale
        return _parse_localename(localename)
      File "/Users/rubenbakker/anaconda/lib/python2.7/locale.py", line 477, in _parse_localename
        raise ValueError, 'unknown locale: %s' % localename
    ValueError: unknown locale: UTF-8
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-p12Yma/dendropy/

using the commands: 

>>> cd 
>>> git clone git://github.com/jeetsukumaran/DendroPy.git
>>> sudo python setup.py develop

I receive the same error message as using pip. 

Do other people experience the same issues when installing dendropy? Has the library been discontinued? 

Thank you for reading this far down my post.

Ruben

**Comment by jeetsukumaran** [comment] 2017-01-13 15:09
As a general tip, if you want to assess the currency of a project on GitHub, you could take look at the commits tab to get an idea of the volume and recency of commits. With DendroPy, you can see that there were a number of commits on the master branch a couple of weeks ago, and some on the development branch a few days ago, including a major end-use application (sumlabels). Whether this tempo indicates to you that the library has been discontinued is your call. On our side, I can say that as far as we know, the answer is "no".

To you installation issues. I tried installing DendroPy under Python 2.7 using pip on a fresh box, and faced no difficulties. Same with 3.4. The problem with 3.5 is that the master branch setup.py did not include that release of Python; this has been fixed in the development branch. 

Looking at the stack trace, it seems that the problem is that your Python installation (through Anaconda) fails in the call to ``getlocale()''. If this is indeed the case, then the following should give you an error:

    python -c "import locale; print(locale.getdefaultlocale())"

whereas it does not on pretty much any Python installation that I have access to. If you find the above gives you an error, then the problem is on your side of things. In particular, you have not set up the locale in your shell. See [here](http://stackoverflow.com/a/15591007) for details (http://stackoverflow.com/a/15591007).

**Comment by Ruubster** [comment] 2017-01-14 12:44
Well thank you so much jeetsukumaran, it worked!

I am pretty new to programming. You're tips just helped me a lot, not just for installing DendroPy. 

Thanks for taking the time out to comment on my message!

**Comment by jeetsukumaran** [comment] 2017-01-14 21:19
No problem. Thanks for bringing the issue to our attention so it can be addressed.

For what it's worth, an undefined environment locale should not cause any issues with this fix: 25e8204 .

And, the anaconda installation failure requires that the upstream repository maintainer update on their end: http://stackoverflow.com/a/41651584/268330 .

**Closed by jeetsukumaran** 2017-01-14 21:19 UTC
